baseURL = "https://solosoyfranco.github.io/"
languageCode = "en-US"
title = "Just Franco"
theme = "mostafa-hugo-theme"
defaultContentLanguage = "en"
enableRobotsTXT = true



[module]
[module.hugoVersion]
  extended = true
  min = "0.116.0"


[menus]

[[menus.main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[menus.main]]
  name = "Blog"
  pageRef = "/blog"
  weight = 20

[[menus.main]]
  name = "Projects"
  pageRef = "/projects"
  weight = 30

[[menus.main]]
  name = "Resume"
  pageRef = "/resume"
  weight = 40

[[menus.main]]
  name = "Homelab"
  pageRef = "/categories/homelab"
  weight = 50

[params]
  author = "Franco Lopez"
  description = "IT Manager, Full-Stack Developer, 3D Printing & VR Enthusiast"
  keywords = "IT, Django, React, DevOps, Homelab, Kubernetes, VR, 3D Printing, Cybersecurity"
  subtitle = "Modern tech. Old-school curiosity."
  showSubtitle = true
  paginate = 10
  resizeImages = true
  enableHighlightJs = true
  showReadingTime = true
  tocMinWordCount = 300
  dateFormat = "January 2, 2006"

  # Dark color palette with cyan & coral accent
  baseColor = "#111827"
  pageBackgroundColor = "$base-color"
  specialColor = "#1f2937"
  highlightColor = "#10B981"
  textColor = "#d1d5db"
  navBackgroundColor = "#1F2937"
  navTextColor = "#ffffff"
  headerTextColor = "#10B981"

  # Social links (FontAwesome icons)
  socialMediaLinks = [
    { name = "GitHub", link = "https://github.com/solosoyfranco", icon = "fab fa-github" },
    { name = "LinkedIn", link = "https://linkedin.com/in/jfranco-lopez", icon = "fab fa-linkedin" },
    { name = "Email", link = "mailto:jfrancolopez.dev@gmail.com", icon = "fas fa-envelope" },
    { name = "3D Projects", link = "https://www.printables.com/@Franco_443073", icon = "fas fa-cube" }
  ]

  otherLinks = [
    { name = "StartBlue Quote Tool", link = "https://startblue.lstractorusa.com" },
    { name = "Homelab Logs", link = "/categories/homelab" }
  ]

  showFooter = true
  amountLatestPostsInFooter = 5
  amountCategoriesInFooter = 5

[Languages]
  [Languages.en]
    weight = 1
    languageCode = "en-US"
    languageName = "English"
    [Languages.en.params]
      subtitle = "Modern tech. Old-school curiosity."

  [Languages.es]
    weight = 2
    languageCode = "es-ES"
    languageName = "Español"
    [Languages.es.params]
      subtitle = "Papá, Ingeniero y creador."

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[taxonomies]
  category = "categories"
  tag = "tags"
  project = "projects"

[outputs]
  home = [ "HTML", "RSS", "JSON" ]
  page = [ "HTML", "RSS" ]
